# Site wide configuration

title:            A Common Man's Guide to Trading Options
locale:           en_US
#url:             http://manojrajarao.github.io
url:             http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Manoj Raja Rao
  avatar: bio-photo.jpg
  bio: "Your Average Common Man"
  email: manoj@manojrajarao.com
  disqus-shortname: 
  twitter: manojrajarao
  facebook: #username
  google:
    plus: manojrajarao
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: manojrajarao
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
